### PR TITLE
Discuss fix for 129

### PR DESCRIPTION
**Pull request by iiegn**
This PR includes the configuration for the JavaScript linter [eslint](https://eslint.org/) and the output of an automated linting on the two files:
 - `website/lexonomy.js`
 - `website/ops.js`

The configuration (and therefore the automated linting) makes some things explicit:
 - semicolons are mandatory
 - strings should be defined with double quotes (unless double quotes are part of the string, then single quotes can be used)
 - the use of the type-safe equality operators `===` and `!==` instead of their regular counterparts `==` and `!=` is enforced

Following is the list of 'error'-s the linter could not fix *automatically* - these will therefore still show up in a linter run:
```
/opt/service/website/ops.js
     7:7    error  'nodemailer' is assigned a value but never used  no-unused-vars
    11:7    error  Identifier 'find_process' is not in camel case   camelcase
    28:44   error  Expected '!==' and instead saw '!='              eqeqeq
    31:38   error  Expected '!==' and instead saw '!='              eqeqeq
    34:38   error  Expected '!==' and instead saw '!='              eqeqeq
    54:118  error  Expected error to be handled                     handle-callback-err
    75:145  error  Expected error to be handled                     handle-callback-err
   125:144  error  Expected error to be handled                     handle-callback-err
   158:24   error  'config' was used before it was defined          no-use-before-define
   163:12   error  Expected '===' and instead saw '=='              eqeqeq
   164:12   error  Expected '===' and instead saw '=='              eqeqeq
   165:12   error  Expected '===' and instead saw '=='              eqeqeq
   166:12   error  Expected '===' and instead saw '=='              eqeqeq
   167:12   error  Expected '===' and instead saw '=='              eqeqeq
   171:70   error  Expected error to be handled                     handle-callback-err
   173:122  error  Expected error to be handled                     handle-callback-err
   177:71   error  Expected error to be handled                     handle-callback-err
   178:130  error  Expected error to be handled                     handle-callback-err
   185:20   error  Expected '===' and instead saw '=='              eqeqeq
   185:43   error  Expected '===' and instead saw '=='              eqeqeq
   190:27   error  Expected '===' and instead saw '=='              eqeqeq
   190:52   error  Expected '===' and instead saw '=='              eqeqeq
   190:77   error  Expected '===' and instead saw '=='              eqeqeq
   194:27   error  Expected '===' and instead saw '=='              eqeqeq
   205:11   error  Identifier 'sql_random' is not in camel case     camelcase
   206:51   error  Expected error to be handled                     handle-callback-err
   237:68   error  Expected error to be handled                     handle-callback-err
   258:139  error  Expected error to be handled                     handle-callback-err
   262:10   error  Expected error to be handled                     handle-callback-err
   271:12   error  Expected error to be handled                     handle-callback-err
   278:61   error  Expected '===' and instead saw '=='              eqeqeq
   309:12   error  Expected error to be handled                     handle-callback-err
   317:74   error  Expected error to be handled                     handle-callback-err
   319:63   error  Expected '===' and instead saw '=='              eqeqeq
   320:62   error  Unnecessary escape character: \"                 no-useless-escape
   320:64   error  Unnecessary escape character: \'                 no-useless-escape
   320:96   error  Unnecessary escape character: \"                 no-useless-escape
   320:98   error  Unnecessary escape character: \'                 no-useless-escape
   320:119  error  Unnecessary escape character: \=                 no-useless-escape
   320:122  error  Unnecessary escape character: \"                 no-useless-escape
   320:127  error  Unnecessary escape character: \"                 no-useless-escape
   320:132  error  Unnecessary escape character: \"                 no-useless-escape
   324:143  error  Expected error to be handled                     handle-callback-err
   334:14   error  Expected error to be handled                     handle-callback-err
   343:16   error  Expected error to be handled                     handle-callback-err
   352:74   error  Expected error to be handled                     handle-callback-err
   354:63   error  Expected '===' and instead saw '=='              eqeqeq
   357:48   error  Unnecessary escape character: \"                 no-useless-escape
   357:50   error  Unnecessary escape character: \'                 no-useless-escape
   357:82   error  Unnecessary escape character: \"                 no-useless-escape
   357:84   error  Unnecessary escape character: \'                 no-useless-escape
   357:105  error  Unnecessary escape character: \=                 no-useless-escape
   357:108  error  Unnecessary escape character: \"                 no-useless-escape
   357:113  error  Unnecessary escape character: \"                 no-useless-escape
   357:118  error  Unnecessary escape character: \"                 no-useless-escape
   358:65   error  Unnecessary escape character: \"                 no-useless-escape
   358:67   error  Unnecessary escape character: \'                 no-useless-escape
   358:99   error  Unnecessary escape character: \"                 no-useless-escape
   358:101  error  Unnecessary escape character: \'                 no-useless-escape
   358:122  error  Unnecessary escape character: \=                 no-useless-escape
   358:125  error  Unnecessary escape character: \"                 no-useless-escape
   358:130  error  Unnecessary escape character: \"                 no-useless-escape
   358:135  error  Unnecessary escape character: \"                 no-useless-escape
   361:27   error  Expected '===' and instead saw '=='              eqeqeq
   365:145  error  Expected error to be handled                     handle-callback-err
   375:16   error  Expected error to be handled                     handle-callback-err
   379:18   error  Expected error to be handled                     handle-callback-err
   388:18   error  Expected error to be handled                     handle-callback-err
   407:75   error  Expected '!==' and instead saw '!='              eqeqeq
   413:36   error  Expected '!==' and instead saw '!='              eqeqeq
   414:159  error  Expected error to be handled                     handle-callback-err
   433:62   error  Expected error to be handled                     handle-callback-err
   435:121  error  Expected error to be handled                     handle-callback-err
   444:163  error  Expected error to be handled                     handle-callback-err
   457:20   error  'i' is already defined                           no-redeclare
   460:15   error  'els' is already defined                         no-redeclare
   462:17   error  '_els' is already defined                        no-redeclare
   463:22   error  'i' is already defined                           no-redeclare
   465:59   error  Expected '===' and instead saw '=='              eqeqeq
   467:62   error  Expected '===' and instead saw '=='              eqeqeq
   476:89   error  Expected error to be handled                     handle-callback-err
   486:146  error  Expected error to be handled                     handle-callback-err
   489:200  error  Expected error to be handled                     handle-callback-err
   500:146  error  Expected error to be handled                     handle-callback-err
   502:160  error  Expected error to be handled                     handle-callback-err
   511:112  error  Expected error to be handled                     handle-callback-err
   525:233  error  Expected error to be handled                     handle-callback-err
   541:21   error  'el' is already defined                          no-redeclare
   551:83   error  Expected error to be handled                     handle-callback-err
   565:19   error  'els' is already defined                         no-redeclare
   566:24   error  'i' is already defined                           no-redeclare
   581:61   error  Expected '===' and instead saw '=='              eqeqeq
   583:79   error  Expected error to be handled                     handle-callback-err
   605:38   error  Expected '!==' and instead saw '!='              eqeqeq
   625:94   error  'entryXML' is already defined                    no-redeclare
   627:20   error  Expected '===' and instead saw '=='              eqeqeq
   629:20   error  Expected '===' and instead saw '=='              eqeqeq
   643:27   error  Expected '===' and instead saw '=='              eqeqeq
   644:13   error  'sql1' is already defined                        no-redeclare
   651:13   error  'params1' is already defined                     no-redeclare
   652:13   error  'sql2' is already defined                        no-redeclare
   656:13   error  'params2' is already defined                     no-redeclare
   657:27   error  Expected '===' and instead saw '=='              eqeqeq
   658:13   error  'sql1' is already defined                        no-redeclare
   665:13   error  'params1' is already defined                     no-redeclare
   666:13   error  'sql2' is already defined                        no-redeclare
   670:13   error  'params2' is already defined                     no-redeclare
   712:41   error  Expected '===' and instead saw '=='              eqeqeq
   718:9    error  'ret' is already defined                         no-redeclare
   722:17   error  Expected '!==' and instead saw '!='              eqeqeq
   728:36   error  Identifier 'headword_elem' is not in camel case  camelcase
   734:13   error  Expected '===' and instead saw '=='              eqeqeq
   737:13   error  Expected '===' and instead saw '=='              eqeqeq
   760:14   error  'i' is already defined                           no-redeclare
   777:34   error  Expected '!==' and instead saw '!='              eqeqeq
   777:60   error  Expected '===' and instead saw '=='              eqeqeq
   786:11   error  Identifier 'sql_before' is not in camel case     camelcase
   791:11   error  Identifier 'sql_after' is not in camel case      camelcase
   797:65   error  Expected error to be handled                     handle-callback-err
   801:66   error  Expected error to be handled                     handle-callback-err
   812:11   error  Identifier 'sql_before' is not in camel case     camelcase
   817:11   error  Identifier 'sql_after' is not in camel case      camelcase
   822:61   error  Expected '===' and instead saw '=='              eqeqeq
   825:78   error  Expected error to be handled                     handle-callback-err
   829:79   error  Expected error to be handled                     handle-callback-err
   841:11   error  Identifier 'sql_randoms' is not in camel case    camelcase
   842:11   error  Identifier 'sql_total' is not in camel case      camelcase
   845:67   error  Expected error to be handled                     handle-callback-err
   849:31   error  Expected error to be handled                     handle-callback-err
   859:11   error  Identifier 'sql_list' is not in camel case       camelcase
   868:106  error  Expected error to be handled                     handle-callback-err
   871:89   error  Expected '===' and instead saw '=='              eqeqeq
   871:114  error  Expected '===' and instead saw '=='              eqeqeq
   880:68   error  Expected error to be handled                     handle-callback-err
   891:15   error  Identifier 'sql_after' is not in camel case      camelcase
   896:47   error  Expected error to be handled                     handle-callback-err
   898:17   error  Identifier 'sql_before' is not in camel case     camelcase
   903:50   error  Expected error to be handled                     handle-callback-err
   918:50   error  Expected error to be handled                     handle-callback-err
   919:9    error  'xml' is not defined                             no-undef
   920:9    error  'xml' is not defined                             no-undef
   920:49   error  'xml' is not defined                             no-undef
   921:19   error  'xml' is not defined                             no-undef
   922:10   error  Expected error to be handled                     handle-callback-err
   933:8    error  Expected error to be handled                     handle-callback-err
   934:49   error  Expected error to be handled                     handle-callback-err
   941:41   error  Identifier 'pid_data' is not in camel case       camelcase
   943:9    error  Identifier 'pid_data' is not in camel case       camelcase
   950:75   error  Expected '===' and instead saw '=='              eqeqeq
   971:7    error  'progress' is not defined                        no-undef
   974:9    error  Identifier 'pidfile_fd' is not in camel case     camelcase
   974:9    error  'pidfile_fd' is not defined                      no-undef
   975:9    error  Identifier 'errfile_fd' is not in camel case     camelcase
   975:9    error  'errfile_fd' is not defined                      no-undef
   978:9    error  'progress' is not defined                        no-undef
   981:101  error  Identifier 'pidfile_fd' is not in camel case     camelcase
   981:101  error  'pidfile_fd' is not defined                      no-undef
   981:113  error  Identifier 'errfile_fd' is not in camel case     camelcase
   981:113  error  'errfile_fd' is not defined                      no-undef
   992:129  error  Expected error to be handled                     handle-callback-err
  1000:132  error  Expected error to be handled                     handle-callback-err
  1011:116  error  Expected error to be handled                     handle-callback-err
  1016:39   error  Identifier 'ske_userName' is not in camel case   camelcase
  1018:140  error  Expected error to be handled                     handle-callback-err
  1023:37   error  Identifier 'ske_apiKey' is not in camel case     camelcase
  1025:132  error  Expected error to be handled                     handle-callback-err
  1032:120  error  Expected error to be handled                     handle-callback-err
  1039:91   error  Expected error to be handled                     handle-callback-err
  1040:15   error  Expected '===' and instead saw '=='              eqeqeq
  1051:224  error  Expected error to be handled                     handle-callback-err
  1052:138  error  Expected error to be handled                     handle-callback-err
  1064:91   error  Expected error to be handled                     handle-callback-err
  1076:224  error  Expected error to be handled                     handle-callback-err
  1077:138  error  Expected error to be handled                     handle-callback-err
  1089:140  error  Expected error to be handled                     handle-callback-err
  1096:136  error  Expected error to be handled                     handle-callback-err
  1099:77   error  Expected error to be handled                     handle-callback-err
  1100:19   error  Expected '===' and instead saw '=='              eqeqeq
  1102:116  error  Expected error to be handled                     handle-callback-err
  1103:159  error  Expected error to be handled                     handle-callback-err
  1117:136  error  Expected error to be handled                     handle-callback-err
  1121:106  error  Expected error to be handled                     handle-callback-err
  1122:155  error  Expected error to be handled                     handle-callback-err
  1136:314  error  Expected error to be handled                     handle-callback-err
  1144:92   error  Expected error to be handled                     handle-callback-err
  1147:79   error  Expected error to be handled                     handle-callback-err
  1148:21   error  Expected '===' and instead saw '=='              eqeqeq
  1151:335  error  Expected error to be handled                     handle-callback-err
  1161:15   error  'email' is already defined                       no-redeclare
  1164:204  error  Expected error to be handled                     handle-callback-err
  1176:209  error  Expected error to be handled                     handle-callback-err
  1182:13   error  Identifier 'ske_username' is not in camel case   camelcase
  1183:13   error  Identifier 'ske_apiKey' is not in camel case     camelcase
  1186:25   error  Expected '===' and instead saw '=='              eqeqeq
  1188:102  error  Expected error to be handled                     handle-callback-err
  1198:15   error  Expected '!==' and instead saw '!='              eqeqeq
  1199:192  error  Expected error to be handled                     handle-callback-err
  1205:9    error  Identifier 'ske_apiKey' is not in camel case     camelcase
  1205:9    error  'ske_apiKey' is not defined                      no-undef
  1206:9    error  Identifier 'ske_username' is not in camel case   camelcase
  1206:9    error  'ske_username' is not defined                    no-undef
  1208:102  error  Expected error to be handled                     handle-callback-err
  1211:75   error  Expected '===' and instead saw '=='              eqeqeq
  1218:234  error  'ske_username' is not defined                    no-undef
  1218:260  error  'ske_apiKey' is not defined                      no-undef
  1227:138  error  Expected error to be handled                     handle-callback-err
  1236:36   error  Expected error to be handled                     handle-callback-err
  1260:121  error  Expected error to be handled                     handle-callback-err
  1273:118  error  Expected error to be handled                     handle-callback-err
  1279:24   error  Expected '===' and instead saw '=='              eqeqeq
  1296:45   error  Identifier 'ske_username' is not in camel case   camelcase
  1296:59   error  Identifier 'ske_apiKey' is not in camel case     camelcase
  1298:9    error  Identifier 'ske_username' is not in camel case   camelcase
  1298:22   error  Expected '!==' and instead saw '!='              eqeqeq
  1298:31   error  Identifier 'ske_apiKey' is not in camel case     camelcase
  1298:42   error  Expected '!==' and instead saw '!='              eqeqeq
  1347:54   error  Expected error to be handled                     handle-callback-err
  1353:37   error  Expected error to be handled                     handle-callback-err
  1362:87   error  Expected error to be handled                     handle-callback-err
  1366:166  error  Expected error to be handled                     handle-callback-err
  1367:11   error  'xml' is not defined                             no-undef
  1367:40   error  'xml' is not defined                             no-undef
  1367:79   error  'xml' is not defined                             no-undef
  1369:13   error  'xml' is not defined                             no-undef
  1371:11   error  'xml' is not defined                             no-undef
  1373:27   error  'xml' is not defined                             no-undef
  1382:8    error  Expected error to be handled                     handle-callback-err
  1395:8    error  Expected error to be handled                     handle-callback-err
  1410:10   error  Expected error to be handled                     handle-callback-err
  1420:92   error  Expected error to be handled                     handle-callback-err
  1432:8    error  Expected error to be handled                     handle-callback-err
  1443:54   error  Expected error to be handled                     handle-callback-err
  1449:37   error  Expected error to be handled                     handle-callback-err
  1458:73   error  Expected error to be handled                     handle-callback-err
  1462:165  error  Expected error to be handled                     handle-callback-err
  1463:11   error  'xml' is not defined                             no-undef
  1465:13   error  'xml' is not defined                             no-undef
  1467:11   error  'xml' is not defined                             no-undef
  1469:24   error  'xml' is not defined                             no-undef
  1477:107  error  Expected error to be handled                     handle-callback-err
  1498:111  error  Expected error to be handled                     handle-callback-err
  1534:7    error  Identifier 'flag_exists' is not in camel case    camelcase
  1536:5    error  Identifier 'flag_exists' is not in camel case    camelcase
  1539:7    error  Identifier 'flag_exists' is not in camel case    camelcase
  1547:28   error  Unnecessary escape character: \/                 no-useless-escape
  1548:28   error  Unnecessary escape character: \/                 no-useless-escape
  1548:55   error  Unnecessary escape character: \"                 no-useless-escape
  1548:57   error  Unnecessary escape character: \'                 no-useless-escape
  1549:28   error  Unnecessary escape character: \/                 no-useless-escape
  1549:58   error  Unnecessary escape character: \"                 no-useless-escape
  1549:60   error  Unnecessary escape character: \'                 no-useless-escape
  1551:39   error  Unnecessary escape character: \/                 no-useless-escape
  1553:48   error  Unnecessary escape character: \/                 no-useless-escape
  1554:49   error  Unnecessary escape character: \/                 no-useless-escape
  1555:29   error  Unnecessary escape character: \/                 no-useless-escape
  1561:28   error  Unnecessary escape character: \/                 no-useless-escape
  1570:11   error  Expected '!==' and instead saw '!='              eqeqeq
  1578:13   error  Expected '===' and instead saw '=='              eqeqeq
  1578:25   error  Expected '===' and instead saw '=='              eqeqeq
  1580:13   error  Expected '!==' and instead saw '!='              eqeqeq

/opt/service/website/lexonomy.js
    18:7   error  'querystring' is assigned a value but never used                             no-unused-vars
    20:7   error  'sqlite3' is assigned a value but never used                                 no-unused-vars
    33:93  error  Expected '===' and instead saw '=='                                          eqeqeq
    37:88  error  Expected error to be handled                                                 handle-callback-err
   207:39  error  'adjustedEntryID' is not defined                                             no-undef
   207:65  error  'json' is not defined                                                        no-undef
   285:46  error  Expected '!==' and instead saw '!='                                          eqeqeq
   339:46  error  Expected '!==' and instead saw '!='                                          eqeqeq
   358:26  error  Expected '!==' and instead saw '!='                                          eqeqeq
   423:24  error  Expected '===' and instead saw '=='                                          eqeqeq
   434:70  error  'i' is already defined                                                       no-redeclare
   435:54  error  'i' is already defined                                                       no-redeclare
   444:31  error  Expected '===' and instead saw '=='                                          eqeqeq
   490:31  error  Expected '===' and instead saw '=='                                          eqeqeq
   529:27  error  Expected '===' and instead saw '=='                                          eqeqeq
   554:30  error  Expected '===' and instead saw '=='                                          eqeqeq
   600:78  error  Expected '===' and instead saw '=='                                          eqeqeq
   601:71  error  Expected '===' and instead saw '=='                                          eqeqeq
   636:25  error  Expected '===' and instead saw '=='                                          eqeqeq
   799:7   error  Move function declaration to function body root                              no-inner-declarations
  1022:39  error  Expected '===' and instead saw '=='                                          eqeqeq
  1049:25  error  'url.parse' was deprecated since v11.0.0. Use 'url.URL' constructor instead  node/no-deprecated-api
  1065:23  error  'url.parse' was deprecated since v11.0.0. Use 'url.URL' constructor instead  node/no-deprecated-api
  1101:31  error  Expected '===' and instead saw '=='                                          eqeqeq
  1230:18  error  Expected '!==' and instead saw '!='                                          eqeqeq
  1299:86  error  Expected error to be handled                                                 handle-callback-err

✖ 286 problems (286 errors, 0 warnings)
```

### CODE REVIEW

**Comment by iiegn** [comment]
assigned this PR to all relevant people from last week's hackathon. pls. comment!

**Comment by gareins** [comment]
I actually would even prefer stricter rules, but this is a good start :)

**Comment by iiegn** [comment]
ah, yes! i forgot to mention (in the PR) that there are plenty of code style guidelines. Some possibilities are:
 - [google](https://google.github.io/styleguide/jsguide.html)
 - [airbnb](https://github.com/airbnb/javascript)
 - [JavaScript Standard Style](https://github.com/standard/standard)

what i did, was to use [these rules](https://github.com/standard/standard/blob/master/RULES.md#javascript-standard-style) from StandardJS and deviate in the above mentioned points.

**Comment by mjakubicek** [comment]
I guess we can just start with this though I hope there will be much less Javascript soon so this will be much less of a problem :)

**Comment by iiegn** [comment]
although, some browser-part will stay :\ and, of course, there are style guides for 
- [go](https://github.com/golang/go/wiki/CodeReviewComments)
- [python](https://www.python.org/dev/peps/pep-0008/)

(and linters exist, too)

**Comment by mjakubicek** [comment]
yes, sure - on Python, we never had the urge to use any style guides or linters because the language enforces most of what normally these guidelines and tools do (indentation etc.).

Actually, one of the most important things is having the editors setup correctly, e.g. with the .editorconfig or in a way that they honour the formatting of the code that is already present.

**Comment by iiegn** [comment]
#114 took care of putting `.editorconfig` into the repo, and with https://github.com/editorconfig/editorconfig-vim this just works™ for *my* editor ;)

on a related note: i would still run the linter (with a suitable configuration that outputs warnings instead of errors) for commits. what do you think about activating the [free CI for Open Source projects *Travis CI integration*](https://github.com/marketplace/travis-ci/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW43MA==#pricing-and-setup) - the docker-ised version is ready to run the linter...

**Comment by mjakubicek** [comment]
Yes, why not -- I don't have a good overview of available options (internally we use GitLab's builtin CI) so if you think that one works well, that's it.

**Comment by iiegn** [comment]
great! this needs to do someone with [more administrative power over the repository](https://xkcd.com/838/).
following this link: 
* https://github.com/marketplace/travis-ci/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW43MA==#pricing-and-setup
should bring you close to activating it for the repository.

**Comment by mjakubicek** [comment]
:-D Like you for instance (now).

**Comment by iiegn** [comment]
tiny hick-up: CI has to be activated for the whole organization (but i think, i managed to escalate a request to the elexis-eu orga admins...)

**Comment by mjakubicek** [comment]
You did and I've already granted access.

**Comment by iiegn** [comment]
ok, here we go: https://travis-ci.org/elexis-eu/lexonomy/builds/527369340

now, we need to silence the `errors` (either by rewriting code or by turning them into `warnings`).

**Pull request merged**
